### ISSUE TITLE
Error in Group By 

### ISSUE THREAD

**Issue by Timboslice003** [bcongelio/nfl-analytics-with-r-book#9]
Hello, for section 3.5.12 I think there is an issue with this section:

dakota_composite <- nflreadr::[load_player_stats](https://nflreadr.nflverse.com/reference/load_player_stats.html)(2022) %>%
  [filter](https://rdrr.io/r/stats/filter.html)(position == "QB") %>%
  group_by(player_display_name, season) %>%
  summarize(attempts = [sum](https://rdrr.io/r/base/sum.html)(attempts, na.rm = TRUE),
            mean_dakota = [mean](https://rdrr.io/r/base/mean.html)(dakota, na.rm = TRUE)) %>%
  [filter](https://rdrr.io/r/stats/filter.html)(attempts >= 200)

This caused the resulting plot to have a lot more points than the example given. Once I removed season from the group by it worked as expected.

**Update: Nevermind I was doing something wrong.

**Comment by bcongelio** [comment]
I am glad you figured it out.

For reference (in case somebody else runs across this), adding `season` to the `group_by()` typically is not needed. However, because this example is being merged with information from the `load_contracts()` function, we include the season in order to join the information to each player by the associated year.
